/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.bitgyro.kfkstream.map;

import org.junit.Test;
import static org.junit.Assert.*;

public class EmployeeDataStreamAppTest {
    @Test public void testAppHasAGreeting() {
        EmployeeDataStreamApp classUnderTest = new EmployeeDataStreamApp();
    }
}
